version: "3.8"

services:
  server:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    ports:
      - "3000:3000"
    command: npm run start:prod
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres

  front_end:
    build:
      context: ./packages/my-new-project
      dockerfile: Dockerfile
    container_name: front_end
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: npm run start:prod
    depends_on:
      - server
